# Generated by Django 5.2.14 on 2026-05-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antecedentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("diagnostico", models.TextField()),
                ("recomendaciones", models.TextField()),
                ("objetivo", models.TextField()),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("imc", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gc", models.DecimalField(decimal_places=2, max_digits=5)),
                ("mm", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_prox_consulta", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DetalleRutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.CharField(max_length=9)),
                ("repeticiones", models.CharField(max_length=2)),
                ("serie", models.CharField(max_length=2)),
                ("peso", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("grupo", models.IntegerField()),
                ("cupo", models.IntegerField()),
                ("hora_inicial", models.TextField()),
                ("hora_final", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.CharField(max_length=9)),
                ("hora_inicial", models.TimeField()),
                ("hora_final", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Rutina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("observaciones", models.TextField()),
                ("objetivo", models.TextField()),
                ("fecha_prox_consulta", models.DateField()),
            ],
        ),
    ]
