# Generated by Django 5.2.14 on 2026-05-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actividades", "0001_initial"),
        ("core", "0001_initial"),
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antecedentes",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
            ),
        ),
        migrations.AddField(
            model_name="antecedentes",
            name="nutricionista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.nutricionista"
            ),
        ),
        migrations.AddField(
            model_name="detallerutina",
            name="ejercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.ejercicio"
            ),
        ),
        migrations.AddField(
            model_name="horario",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.disciplina"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finanzas.comprobante"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.disciplina"
            ),
        ),
        migrations.AddField(
            model_name="detallerutina",
            name="rutina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.rutina"
            ),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.sala"
            ),
        ),
        migrations.AddField(
            model_name="seguimiento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
            ),
        ),
        migrations.AddField(
            model_name="seguimiento",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.instructor"
            ),
        ),
        migrations.AddField(
            model_name="seguimiento",
            name="rutina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actividades.rutina"
            ),
        ),
    ]
