# Generated by Django 5.2.14 on 2026-05-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(max_length=1)),
                ("fecha_ini", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membresia", models.CharField(max_length=20)),
                ("plan", models.CharField(max_length=10)),
                ("descripcion", models.CharField(max_length=40)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodo_pago", models.CharField(max_length=1)),
                ("fecha", models.DateField()),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado_pago", models.CharField(max_length=10)),
                (
                    "administrador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.administrativo",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finanzas.promocion",
                    ),
                ),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.suscripcion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_ini_mem", models.DateField()),
                ("fecha_fin_mem", models.DateField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="finanzas.pago"
                    ),
                ),
            ],
        ),
    ]
