# Generated by Django 5.2.6 on 2026-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
