# Generated by Django 5.2.6 on 2026-06-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente_domicilio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora",
                "verbose_name_plural": "Bitácoras",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]





