# Generated by Django 5.2.14 on 2026-06-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bitacora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bitacora",
            options={
                "ordering": ["-fecha_hora"],
                "verbose_name": "BitÃ¡cora",
                "verbose_name_plural": "BitÃ¡coras",
            },
        ),
    ]
